/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lesson10.insertRemove;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author evan8510
 */
public class ArrayListPersonGUI extends javax.swing.JFrame {

    
    DefaultListModel model= new DefaultListModel();
    ArrayList<Person> peeps = new ArrayList();
    
    public ArrayListPersonGUI() {
        initComponents();
        lstPeeps.setModel(model);
        rbutMale.setActionCommand("Male");
        rbutFem.setActionCommand("Female");
        peeps.add(new Person("Andy", 45, "Male"));
        peeps.add(new Person("Deb", 55, "Female"));
        peeps.add(new Person("Mike", 17, "Male"));
        peeps.add(new Person("Sue", 28, "Female"));
        
        for (Person p : peeps) {
            model.addElement(p.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPeeps = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbutMale = new javax.swing.JRadioButton();
        rbutFem = new javax.swing.JRadioButton();
        txtAge = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemClear = new javax.swing.JMenuItem();
        itemAdd = new javax.swing.JMenuItem();
        itemDel = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemShow = new javax.swing.JMenuItem();
        itemFem = new javax.swing.JMenuItem();
        itemMale = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("People ArrayList");

        lstPeeps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPeepsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstPeeps);

        jLabel1.setText("Name:");

        jLabel2.setText("Age:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(rbutMale);
        rbutMale.setText("Male");

        buttonGroup1.add(rbutFem);
        rbutFem.setText("Female");
        rbutFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutFemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(rbutMale, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbutFem)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbutMale)
                    .addComponent(rbutFem))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        itemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lesson10/insertRemove/x2.jpg"))); // NOI18N
        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        jMenu1.add(itemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        itemClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lesson10/insertRemove/broom.jpg"))); // NOI18N
        itemClear.setText("Clear");
        itemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClearActionPerformed(evt);
            }
        });
        jMenu2.add(itemClear);

        itemAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lesson10/insertRemove/add.png.jpg"))); // NOI18N
        itemAdd.setText("Add");
        itemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddActionPerformed(evt);
            }
        });
        jMenu2.add(itemAdd);

        itemDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lesson10/insertRemove/delete.png"))); // NOI18N
        itemDel.setText("Delete");
        itemDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDelActionPerformed(evt);
            }
        });
        jMenu2.add(itemDel);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Filter");

        itemShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lesson10/insertRemove/smile.jpg"))); // NOI18N
        itemShow.setText("Show All");
        itemShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemShowActionPerformed(evt);
            }
        });
        jMenu3.add(itemShow);

        itemFem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lesson10/insertRemove/female.jpg"))); // NOI18N
        itemFem.setText("Female");
        itemFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFemActionPerformed(evt);
            }
        });
        jMenu3.add(itemFem);

        itemMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lesson10/insertRemove/male.jpg"))); // NOI18N
        itemMale.setText("Male");
        itemMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMaleActionPerformed(evt);
            }
        });
        jMenu3.add(itemMale);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge)
                            .addComponent(txtName))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbutFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutFemActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClearActionPerformed
        clear();
    }//GEN-LAST:event_itemClearActionPerformed

    private void itemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddActionPerformed
        Person temp;
        String gender, name;
        int age;
        try{
        gender = buttonGroup1.getSelection().getActionCommand();
        name = txtName.getText();
        age = Integer.parseInt(txtAge.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please Fill Properly");
            return;
        }
        temp = new Person(name, age, gender);
        int loc = findInsertPoint(peeps, temp);
        peeps.add(loc, temp);
        model.add(loc, temp.getName());
        
    }//GEN-LAST:event_itemAddActionPerformed

    private void itemDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDelActionPerformed
        int sel;
        try{
        sel = lstPeeps.getSelectedIndex();
        peeps.remove(sel);
        model.remove(sel);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Unable to Delete");
            return;
        }
        
    }//GEN-LAST:event_itemDelActionPerformed

    private void itemShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemShowActionPerformed
        model.clear();
        for (Person p : peeps) {
            model.addElement(p.getName());
        }
        itemAdd.setEnabled(true);
        itemDel.setEnabled(true);
    }//GEN-LAST:event_itemShowActionPerformed

    private void itemFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFemActionPerformed
        model.clear();
        for (Person p : peeps) {
            if(p.isFemale())model.addElement(p.getName());
        }
        itemAdd.setEnabled(false);
        itemDel.setEnabled(false);
        clear();
    }//GEN-LAST:event_itemFemActionPerformed

    private void itemMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMaleActionPerformed
        model.clear();
        for (Person p : peeps) {
            if(!p.isFemale())model.addElement(p.getName());
        }
        itemAdd.setEnabled(false);
        itemDel.setEnabled(false);
        clear();
    }//GEN-LAST:event_itemMaleActionPerformed

    private void lstPeepsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPeepsMouseClicked
        String nm = lstPeeps.getSelectedValue();
        Person temp = peeps.get(search(peeps, new Person(nm)));
        show(temp);
    }//GEN-LAST:event_lstPeepsMouseClicked

    public void show(Person p){
        txtAge.setText("" + p.getAge());
        txtName.setText(p.getName());
        rbutFem.setSelected(p.isFemale());
        rbutMale.setSelected(!p.isFemale());
    }
    
    public void clear(){
        buttonGroup1.clearSelection();
        txtAge.setText("");
        txtName.setText("");
        lstPeeps.clearSelection();
    }
    
    public static int findInsertPoint(ArrayList a, Object searchValue) {
        int left = 0;
        int right = a.size() - 1;
        int midpoint = 0;

        while (left <= right) {
            midpoint = (left + right) / 2;

            int result = ((Comparable) a.get(midpoint)).compareTo(searchValue);

            if (result < 0) {
                left = midpoint + 1;
            } else {
                right = midpoint - 1;
            }
        }
        if (((Comparable) a.get(midpoint)).compareTo(searchValue) < 0) {
            midpoint++;
        }
        return midpoint;
    }
    
    public static int search(ArrayList a, Object searchValue) {
        int left = 0;
        int right = a.size() - 1;
        while (left <= right) {
            int midpoint = (left + right) / 2;
            int result = ((Comparable) a.get(midpoint)).compareTo(searchValue);
            if (result == 0) {
                return midpoint;
            } else if (result < 0) {
                left = midpoint + 1;
            } else {
                right = midpoint - 1;
            }
        }
        return -1;

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArrayListPersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArrayListPersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArrayListPersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArrayListPersonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArrayListPersonGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem itemAdd;
    private javax.swing.JMenuItem itemClear;
    private javax.swing.JMenuItem itemDel;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemFem;
    private javax.swing.JMenuItem itemMale;
    private javax.swing.JMenuItem itemShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstPeeps;
    private javax.swing.JRadioButton rbutFem;
    private javax.swing.JRadioButton rbutMale;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
